### ISSUE TITLE
Can not create stack in us-east-1

### ISSUE THREAD

**Issue by hideokamoto** [aws-samples/webauthn-with-amazon-cognito#1]
I tried to create the stack in the us-east-1 region.
But I got the error.

```
Error occurred while GetObject. S3 Error Code: PermanentRedirect. S3 Error Message: The bucket is in this region: us-west-2. Please use this region to retry the request (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 456dd2f2-8ac0-47dd-af41-b61f2a6025c8; Proxy: null)
```

I think the template must run in us-west-2, and we need to add the notification in the README.md

**Comment by mmatouk** [comment]
hi @hideokamoto - if you want to run the template in another region other than us-west-2 you need to download the lambda packages and host them in a bucket in the region where you want to create the stack. you need to update the template to read from the newly created s3 bucket.

**Comment by hideokamoto** [comment]
Thanks.
I think we can update the Readme by the PR.
docs: define the region of cloudformation #2

And probably we can make a similar application by using AWS Amplify.
I'll try it :)

**Comment by mmatouk** [comment]
Yes, definitely can be done with Amplify.
